language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: AOITJgLEfWJXSedEmZYPkDNbBHA6KJLjs3luK/lC2QPoR+Q3a1Bs+iVvZvB3lUHcBVkRdLr8O3QeZ6WWZffl7Yu0BTA0+y07qi5AdIiqcMpMt9t4W4PseuYyoaHPB7m4hwWPaqFK16tkpL4v4BDRQqmwihQx7xRQ21WSD0stu9On2yUqAeEa+s512CY6d3KxUXmaNCNBxNQt/xzD7YgebSFcnppxi1LVYih2SPIN/nn37+RXSLlnme4dQoPkSPsJNWIlFPHK7RU3a92vDikKPz7SwE+VYyEUBHa4GFjWqvGjycKgEeeCjYfSxzizS/vHevF6lwLN5pjc9BJ8V3kp7d000kFrX7AgU91QqA0RZtcqe7u17Mf4kUaO1hsmcY8AKYXyyGqlHerdnRBFOOiSxY/p5ixcRxtopWN2SpZxpvTOgNURFpG7zPFhB0GPR3cTldFkFCR1eSIPBNZr+b0ZgiRfHOVK0tEM+UN7Sn5yOOaQCO+AwC4qrSaMp8XRRNL0uoVE30zjDSkyWeZoNLp5gFFiYLQY18mYO7GHkKEgoCHtvP5TjQFpNKoyTD2/lJNNWwOc3+T63bnAKG5UGK5HdTm3LNxy1ERVCu2eWJcPRfmyhw41fONdHBs15uGZ3BOEuUhDoIJWiTNXTPc1gee595NwvmGl5urxifS7o/kLqMw=
  app: radiant-refuge-10084
  on:
    repo: thejesseshaw/segato-api
